version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: log/autotest.log
            maxBytes: 104857600
            backupCount: 20
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: log/autotest.log
            maxBytes: 104857600
            backupCount: 20
            encoding: utf8
loggers:
       main:
            level: DEBUG
            handlers: [info_file_handler]
            propagate: no
root:
    level: DEBUG
    handlers: [info_file_handler,error_file_handler]
    
